import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.scss'

import { useRef, useState } from 'react'

export default function Home() {
  const inputRef = useRef()
  const [items, setItems] = useState([])
  const [itemsInfos, setItemsInfos] = useState([])

  const handleSubmit = async (event) => {
    event.preventDefault()
    const { value } = inputRef.current
    const response = await fetch(`/api/youtube?q=${value}`)
    const {data} = await response.json()
    setItemsInfos(data)
    setItems(data.items)
  }


  const handleLoadMore = async (event) => {
    event.preventDefault()
    const response = await fetch(`/api/youtube`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json;charset=utf-8'
      },
      body: JSON.stringify(itemsInfos)
    })
    const { data } = await response.json()

    for (let item in data.items) {
      setItems(prev => [...prev, data.items[item]])
    }
  }
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <form className={styles.searchContainer} onSubmit={handleSubmit}>
          <input placeholder='Search...' type='text' ref={inputRef} />
          <button type='submit'>
            <TablerSearch />
          </button>
        </form>

        <div className={styles.cardsContainer} >
          <h2>{inputRef.current?.value}</h2>
          {items?.map(m => {
            if (m.type !== "video") return
            return (
              <div className={styles.card} key={m.id}>
                {/* <Image 
                  alt={m.title} 
                  src={m.thumbnails[0]?.url} 
                  width={m.thumbnails && m.thumbnails[0].width} 
                  height={m.thumbnails && m.thumbnails[0].height} /> */}
                  <div className={styles.iframeContainer}>
                    <iframe
                    title={m.title}
                    loading="lazy"
                    width="730" 
                    height="548" 
                    src={`https://youtube.com/embed/${m.url.split('=')[1]}`} />
                  </div>

                  <Link href={m.url}>
                    <a target='_blank' ><h2>{m.title}</h2></a>
                  </Link>
              </div>
            )
          })}
        </div>

        {items.length > 0 && 
        <button className={styles.loadButton} onClick={handleLoadMore}>Load more...</button>}
       
      </main>

      <footer className={styles.footer}>
          
      </footer>
    </div>
  )
}


export function TablerSearch(props) {
  return (
    <svg width="1.5em" height="1.5em" viewBox="0 0 24 24" {...props}><g fill="none" stroke="rgb(205, 205, 205)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"><circle cx="10" cy="10" r="7"></circle><path d="m21 21l-6-6"></path></g></svg>
  )
}